### ISSUE TITLE
osmcore_L Galaxy Nexus Kernel Panic

### ISSUE THREAD

**Issue by ARoiD** [eolwral/OSMonitor#54]
[ 5623.859741] osmcore_L invoked oom-killer: gfp_mask=0x200da, order=0, oom_adj=-17, oom_score_adj=-1000
[ 5623.859863] Backtrace: 
[ 5623.859985] [<c005c174>] (dump_backtrace+0x0/0x10c) from [<c05d4624>] (dump_stack+0x18/0x1c)
[ 5623.860076]  r6:000200da r5:00000000 r4:c3ada000 r3:00000000
[ 5623.860382] [<c05d460c>] (dump_stack+0x0/0x1c) from [<c01041e8>] (dump_header.isra.7+0x74/0x170)
[ 5623.860504] [<c0104174>] (dump_header.isra.7+0x0/0x170) from [<c0104788>] (out_of_memory+0x248/0x348)
[ 5623.860595]  r8:c3ada000 r7:00000000 r6:0002eed7 r5:00000000 r4:dc9aeac0
[ 5623.860992] [<c0104540>] (out_of_memory+0x0/0x348) from [<c0107dbc>] (__alloc_pages_nodemask+0x748/0x76c)
[ 5623.861053] [<c0107674>] (__alloc_pages_nodemask+0x0/0x76c) from [<c011c95c>] (handle_pte_fault+0x5cc/0xa9c)
[ 5623.861175] [<c011c390>] (handle_pte_fault+0x0/0xa9c) from [<c011ceec>] (handle_mm_fault+0xc0/0x104)
[ 5623.861297] [<c011ce2c>] (handle_mm_fault+0x0/0x104) from [<c00623fc>] (do_page_fault+0x1b8/0x324)
[ 5623.861419] [<c0062244>] (do_page_fault+0x0/0x324) from [<c0052500>] (do_DataAbort+0x3c/0xa0)
[ 5623.861541] [<c00524c4>] (do_DataAbort+0x0/0xa0) from [<c0058608>] (ret_from_exception+0x0/0x10)
[ 5623.861602] Exception stack(0xc3adbfb0 to 0xc3adbff8)
[ 5623.861694] bfa0:                                     5d056000 00000000 0e244c33 00000000
[ 5623.861816] bfc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 bec939ac
[ 5623.861877] bfe0: 00000000 bec93880 00000000 4019f448 200d0010 ffffffff
[ 5623.861999]  r8:00000000 r7:00000000 r6:00000000 r5:00000007 r4:0000040f
[ 5623.862335] Mem-info:
[ 5623.862426] Normal per-cpu:
[ 5623.862487] CPU    0: hi:  186, btch:  31 usd:   0
[ 5623.862548] CPU    1: hi:  186, btch:  31 usd:   0
[ 5623.862670] active_anon:159421 inactive_anon:322 isolated_anon:0
[ 5623.862670]  active_file:15 inactive_file:18 isolated_file:0
[ 5623.862670]  unevictable:378 dirty:0 writeback:0 unstable:0
[ 5623.862670]  free:1396 slab_reclaimable:1199 slab_unreclaimable:4207
[ 5623.862670]  mapped:20794 shmem:331 pagetables:1494 bounce:0
[ 5623.863067] Normal free:3536kB min:3528kB low:15208kB high:16092kB active_anon:637684kB inactive_anon:1288kB active_file:60kB inactive_file:72kB unevictable:1512kB isolated(anon):0kB isolated(file):0kB present:778240kB mlocked:0kB dirty:0kB writeback:0kB mapped:83176kB shmem:1324kB slab_reclaimable:4796kB slab_unreclaimable:16828kB kernel_stack:3080kB pagetables:5976kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:198 all_unreclaimable? yes
[ 5623.863311] lowmem_reserve[]: 0 0 0
[ 5623.863586] Normal: 881*4kB 7*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 3580kB
[ 5623.864379] 766 total pagecache pages
[ 5623.875976] 262144 pages of RAM
[ 5623.876068] 1936 free pages
[ 5623.876129] 69929 reserved pages
[ 5623.876190] 4324 slab pages
[ 5623.876251] 54064 pages shared
[ 5623.876312] 0 pages swap cached
[ 5623.876373] [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
[ 5623.876495] [   97]     0    97      655      137   1     -17         -1000 ueventd
[ 5623.876556] [  124]  1036   124     3784      708   0     -17         -1000 logd
[ 5623.876678] [  125]     0   125      926       86   0     -17         -1000 healthd
[ 5623.876800] [  126]     0   126     1101       80   0     -17         -1000 lmkd
[ 5623.876861] [  127]  1000   127      807       69   1     -17         -1000 servicemanager
[ 5623.876983] [  128]     0   128     2392      187   0     -17         -1000 vold
[ 5623.877105] [  129]  1000   129    17127     6638   0     -17         -1000 surfaceflinger
[ 5623.877166] [  132]  2000   132      797       73   0     -17         -1000 sh
[ 5623.877258] [  133]  1049   133      775       55   1     -17         -1000 auditd
[ 5623.877380] [  134]     0   134     4928      236   1     -17         -1000 netd
[ 5623.877441] [  135]     0   135      950       69   0     -17         -1000 debuggerd
[ 5623.877563] [  136]  1001   136     5013      223   0     -17         -1000 rild
[ 5623.877655] [  137]  1019   137     3887      270   0     -17         -1000 drmserver
[ 5623.877777] [  138]  1013   138    30913     1420   0     -17         -1000 mediaserver
[ 5623.877838] [  139]  1012   139      796       67   1     -17         -1000 installd
[ 5623.877960] [  140]  1017   140     1544      142   1     -17         -1000 keystore
[ 5623.878082] [  142]     0   142   231717     4242   0     -17         -1000 main
[ 5623.878143] [  144]  1023   144     2312      678   1     -17         -1000 sdcard
[ 5623.878234] [  146]  2000   146     1935       91   0     -17         -1000 adbd
[ 5623.878356] [  294]     0   294      797       72   1     -17         -1000 daemonsu
[ 5623.878417] [  324]     0   324     2077       89   0     -17         -1000 daemonsu
[ 5623.878540] [  456]  1000   456   282729    23639   0     -14          -941 system_server
[ 5623.878662] [  568] 10014   568   266299    23389   0     -10          -705 ndroid.systemui
[ 5623.878723] [  632]  1010   632     1578      147   0     -17         -1000 wpa_supplicant
[ 5623.878845] [  784] 10007   784   233786     4347   0     -10          -705 ndroid.incallui
[ 5623.878936] [  792] 10000   792   234115     4836   0     -10          -705 ogenmod.audiofx
[ 5623.879058] [  816]  1001   816   234546     4823   0     -10          -705 .server.telecom
[ 5623.879119] [  838]  1027   838   239081     5137   0     -10          -705 com.android.nfc
[ 5623.879241] [  861]  1001   861   251571    12931   0     -10          -705 m.android.phone
[ 5623.879364] [ 1030]  1014  1030      798       73   1     -17         -1000 dhcpcd
[ 5623.879486] [ 1588]     0  1588     2333      119   1     -17         -1000 daemonsu
[ 5623.879547] [ 2474]     0  2474     2589      121   1     -17         -1000 daemonsu
[ 5623.879638] [16846]     0 16846     2589      121   1     -17         -1000 daemonsu
[ 5623.879791] [17005]     0 17005     2845      137   1     -17         -1000 daemonsu
[ 5623.879852] [17008]     0 17008   176527   117823   1     -17         -1000 osmcore_L
[ 5623.884216] Kernel panic - not syncing: Out of memory and no killable processes...
[ 5623.884216] 
[ 5623.884399] Backtrace: 
[ 5623.884521] [<c005c174>] (dump_backtrace+0x0/0x10c) from [<c05d4624>] (dump_stack+0x18/0x1c)
[ 5623.884643]  r6:0002eed7 r5:c0803800 r4:c08326c0 r3:00000000
[ 5623.884918] [<c05d460c>] (dump_stack+0x0/0x1c) from [<c05d4ac8>] (panic+0x80/0x1b8)
[ 5623.885040] [<c05d4a48>] (panic+0x0/0x1b8) from [<c0104798>] (out_of_memory+0x258/0x348)
[ 5623.885162]  r3:00000002 r2:00000000 r1:e4f42f80 r0:c0735a60
[ 5623.885437]  r7:00000000
[ 5623.885559] [<c0104540>] (out_of_memory+0x0/0x348) from [<c0107dbc>] (__alloc_pages_nodemask+0x748/0x76c)
[ 5623.885681] [<c0107674>] (__alloc_pages_nodemask+0x0/0x76c) from [<c011c95c>] (handle_pte_fault+0x5cc/0xa9c)
[ 5623.885772] [<c011c390>] (handle_pte_fault+0x0/0xa9c) from [<c011ceec>] (handle_mm_fault+0xc0/0x104)
[ 5623.885894] [<c011ce2c>] (handle_mm_fault+0x0/0x104) from [<c00623fc>] (do_page_fault+0x1b8/0x324)
[ 5623.886016] [<c0062244>] (do_page_fault+0x0/0x324) from [<c0052500>] (do_DataAbort+0x3c/0xa0)
[ 5623.886077] [<c00524c4>] (do_DataAbort+0x0/0xa0) from [<c0058608>] (ret_from_exception+0x0/0x10)
[ 5623.886199] Exception stack(0xc3adbfb0 to 0xc3adbff8)
[ 5623.886291] bfa0:                                     5d056000 00000000 0e244c33 00000000
[ 5623.886383] bfc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 bec939ac
[ 5623.886474] bfe0: 00000000 bec93880 00000000 4019f448 200d0010 ffffffff
[ 5623.886596]  r8:00000000 r7:00000000 r6:00000000 r5:00000007 r4:0000040f
[ 5623.886932] CPU0: stopping
[ 5623.887023] Backtrace: 
[ 5623.887145] [<c005c174>] (dump_backtrace+0x0/0x10c) from [<c05d4624>] (dump_stack+0x18/0x1c)
[ 5623.887268]  r6:c07dfad8 r5:fa240100 r4:00000000 r3:00000000
[ 5623.887573] [<c05d460c>] (dump_stack+0x0/0x1c) from [<c0052490>] (do_IPI+0x190/0x1c4)
[ 5623.887664] [<c0052300>] (do_IPI+0x0/0x1c4) from [<c00580c8>] (__irq_svc+0x48/0xe4)
[ 5623.887725] Exception stack(0xd03c3ad0 to 0xd03c3b18)
[ 5623.887847] 3ac0:                                     ef83c3fc 00000080 00000000 eecc54d0
[ 5623.887969] 3ae0: 0000244b eecc5300 fffff5bd 000001b3 c0822654 c07e6ae0 ef83c000 d03c3b8c
[ 5623.888031] 3b00: d03c3b18 d03c3b18 c04275f0 c0427578 200d0113 ffffffff
[ 5623.888153] [<c0427428>] (lowmem_shrink+0x0/0x410) from [<c010d210>] (shrink_slab+0x1f8/0x2d0)
[ 5623.888244] [<c010d018>] (shrink_slab+0x0/0x2d0) from [<c010fb50>] (try_to_free_pages+0x2c8/0x484)
[ 5623.888336] [<c010f888>] (try_to_free_pages+0x0/0x484) from [<c0107a84>] (__alloc_pages_nodemask+0x410/0x76c)
[ 5623.888427] [<c0107674>] (__alloc_pages_nodemask+0x0/0x76c) from [<c0103588>] (filemap_fault+0x268/0x4c0)
[ 5623.888549] [<c0103320>] (filemap_fault+0x0/0x4c0) from [<c0119e0c>] (__do_fault+0x58/0x49c)
[ 5623.888671] [<c0119db4>] (__do_fault+0x0/0x49c) from [<c011c408>] (handle_pte_fault+0x78/0xa9c)
[ 5623.888793] [<c011c390>] (handle_pte_fault+0x0/0xa9c) from [<c011ceec>] (handle_mm_fault+0xc0/0x104)
[ 5623.888854] [<c011ce2c>] (handle_mm_fault+0x0/0x104) from [<c00623fc>] (do_page_fault+0x1b8/0x324)
[ 5623.888916] [<c0062244>] (do_page_fault+0x0/0x324) from [<c00525a0>] (do_PrefetchAbort+0x3c/0xa0)
[ 5623.889038] [<c0052564>] (do_PrefetchAbort+0x0/0xa0) from [<c0058608>] (ret_from_exception+0x0/0x10)
[ 5623.889129] Exception stack(0xd03c3fb0 to 0xd03c3ff8)
[ 5623.889190] 3fa0:                                     00002144 46b261c0 0000003c 00000005
[ 5623.889312] 3fc0: 7115ddab 3c000000 41000000 6fe0c348 00000b17 0000162d 70bab99c 70baba0c
[ 5623.889434] 3fe0: 000010a2 58002800 4205c6f7 41ff7020 800f0030 ffffffff
[ 5623.889495]  r8:00000b17 r7:6fe0c348 r6:41000000 r5:00000007 r4:0000040f
[ 5623.889862] Rebooting in 5 seconds..

**Comment by ARoiD** [comment]
@eolwral Reboots once I enable root and try to view the logs tab

**Comment by eolwral** [comment]
Thanks for information!  

Logcat has changed since Lollipop, the size of logcat becomes large from 64K to 256K, logcat device also becomes 3 named pipes, it is not hard to read data, but serialization is a problem.       

[ 5623.859741] osmcore_L invoked oom-killer: gfp_mask=0x200da, order=0, oom_adj=-17, oom_score_adj=-100

As your log, osmcore invokes oom (Out of memory) killer, because osmcore start to serialize data into binary, it uses mmap function to allocate a large block of memory, unfortunately a disaster is happening, available memory is too small to allocate, system starts to kill other's processes.

[ 5623.884216] Kernel panic - not syncing: Out of memory and no killable processes...

System tells us,  there are no killable processes, then kernel panic...

This issue is the same problem that I am working on now, I think the problem is that I use protocol buffer to serialize data, during serialization it requires large memory, I have tried to use flatbuffer instead of protocol buffer that should solve this problem, if everything works as my expectation, I will release a new version in a couple weeks. :)

Kenney

**Comment by eolwral** [comment]
Hello ARoID,

I have finished a new version which use new serialization library "flatbuffer", which reduces 10% memory, In my phone (Nexus 5 and Android 5.0.1) it works amazing! I still test this version and make sure it is stable, if you would like to help test, you can download it via following link or join beta community. :)
 
How to become a beta tester
1. Join this community (https://plus.google.com/communities/104176911627256834500)
2. Opt-in link (https://play.google.com/apps/testing/com.eolwral.osmonitor)
3. Download beta version via Google Play

Debug Version
> https://drone.io/github.com/eolwral/OSMonitor/files/OSMonitor/bin/OSMonitor-debug.apk

P.S. I will push it as production version, you also can try at that time. :) 

Thanks!

Kenney

**Comment by ARoiD** [comment]
@eolwral Fixed on my Galaxy Nexus running CM12 😉
