### ISSUE TITLE
Wrong filenames / path in install_binary.sh and build.sh

### ISSUE THREAD

**Issue by RealRancor** [eolwral/OSMonitor#56]
Hi,

when running the ndk-build in the OSMonitor subdir the compiled native binaries are located in:

```
libs/armeabi/osmcore
libs/mips/osmcore
libs/x86/osmcore
libs/armeabi/osmcore_pie
libs/mips/osmcore_pie
libs/x86/osmcore_pie
```

https://github.com/eolwral/OSMonitor/blob/master/build.sh uses the correct subdir but the wrong filenames for the build binaries.

https://github.com/eolwral/OSMonitor/blob/master/OSMonitor/jni/install_binary.sh uses the correct filenames but the wrong path (expecting the binaries are located in the jni folder.

**Comment by eolwral** [comment]
Hello, 

Thanks for reminding me! 
I forgot to change filename in build.sh, but install_binary.sh is correct, I always set work directory as "{workspace}/libs", it will work properly. however, I think you are right, the workspace is a default value, it should help others to avoid misunderstanding.  I have pushed a commit to fix it. :)
