### ISSUE TITLE
Question / Request: make APK available outside Google Play

### ISSUE THREAD

**Issue by jerry1970** [eolwral/OSMonitor#59]
Hi,

I am trying to keep my Android device running without a google account - something more and more people appear to do. OS Monitor used to be available in the F-Droid store but it is no longer there. Is there any way to get the APK without a google account? I found an old version here but would love to get the most recent version of course...
https://code.google.com/p/android-os-monitor/downloads/list

Thanks!

**Comment by jerry1970** [comment]
Hm, weird, I get a Not Found error when trying to install from the F-Droid app but can download the APK from the browser...

**Comment by miurahr** [comment]
I can install it from F-Droid today. It looks local repository database of F-Droid is not up-to-date, or temporary broken.

**Comment by jerry1970** [comment]
Works here now, so fixed, thanks.

**Comment by SkyWheel** [comment]
Hi guys,
Please update apk-file in F-Droid repo.
It's very nice when you can install fresh OS Monitor from F-Droid, not from Google Play.
Thanks!
