### ISSUE TITLE
Project structure not Gradle compliant. 

### ISSUE THREAD

**Issue by kevintanhongann** [eolwral/OSMonitor#60]
Sorry for filing this. But Android Studio has been around for some time now. Looking forward to contribute to this open source project when I have free time. 

PS: Thanks for the great tool. It helped me in development a lot.

**Comment by eolwral** [comment]
The migration is done, but the whole procedure isn't finished yet, I will update the wiki later.

**Comment by kevintanhongann** [comment]
@eolwral alright cool. Thanks.

**Comment by eolwral** [comment]
Wiki updated. Closed
