### ISSUE TITLE
Mac address is truncated by one character

### ISSUE THREAD

**Issue by walek75** [eolwral/OSMonitor#61]
On **MISC** tab/**Network**/ info about **MAC** addresesses of network interace are truncated by one character.
It's look like bug in function network::getMACInformation() in network.cc file.
 >line 231: curMACLen = read(curMAC, readBuffer, 17); *// read from /sys/class/net/net_interface_name/address*
 >line 232: strncpy(curMACAddr, readBuffer, 16);

Line 232 it's in my opinion not necessary, because on line 231 takes readings of mac address value and trim it to the right length. Mac Addres length is 16 chars + \0 (end string mark) = 17 chars. strncopy(curMACAddr, readBuffer, 16) cuts last char.
I think that
`line 231: curMACLen = read(curMAC, curMACAddr, 17);` 
`line 232: delete it`
or 
`line 231: curMACLen = read(curMAC, readBuffer, 17);`
`line 232: strncpy(curMACAddr, readBuffer, 17);`
should  be fine

**Comment by eolwral** [comment]
Thanks for fix! currently I am moving the project from Eclipse to Android Studio, I will apply this fix after the migration is done. :)

**Comment by eolwral** [comment]
The patch is pushed, it will be released on the version. Thanks for suggestion. :)

Commit b4d06ed6bd9a310bb46855fdbc0c52ee6915409a
