### ISSUE TITLE
CPU usage animated icon crash

### ISSUE THREAD

**Issue by xphnx** [eolwral/OSMonitor#63]
Hi, I'm the manteiner of a Theme for Cyanogenmod. An user report me an issue with Osmonitor: when enabling the CPU animated icon OSmonitor crashes, maybe an icon missing. Please, see https://gitlab.com/xphnx/twelf_cm12_theme/issues/47
Thanks.

**Comment by eolwral** [comment]
Got it! I will add on next version.

**Comment by eolwral** [comment]
Notification's icon is updated. 

78082cc9b77a226eeb5d98c82630406e8bfe313c
